---
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://choose.correct.ip.address/pong_matcher_spring_development
    username: springpong
    password: springpong
  jpa:
    hibernate.ddl-auto: none
    show_sql: false
